### ISSUE TITLE
DNS Hijack

### ISSUE THREAD

**Issue by asaarashi** [black-desk/cgtproxy#244]
Hi, sorry to bother again but I have another question.

1. Setup a local DNS server on port 5053. I am sure it can receive requests and print out.
2. Spinned up cgtproxy with below configuration:
```
tproxies:
  #......

  v2ray:
    mark: 4000
    port: 12345
    dns-hijack:
      ip: 127.0.0.1
      port: 5053
      tcp: true
```

3. cgtproxy is working well in terms of proxy but I cannot see any request received at the DNS server.

Did I get it wrong?

**Comment by black-desk** [comment]
I test with clash-meta with dns at localhost 5053. It works fine.

clash config:
```yaml
# ...
dns:
  listen: 0.0.0.0:5053
  enable: true
# ...
```

cgtproxy config:
```yaml
# ...
tproxies:
  clash-meta:
    mark: 3000
    port: 7893
    dns-hijack:
      ip: 127.0.0.1
      port: 5053
# ...
```

I think maybe v2ray are hijacking dns too.

You can debug nft rules with cgtproxy build with `debug` tag after 72229af1549df314efdbb5f7934a7f32cb3d3f33 

```bash
# clone repostory
make GO_TAGS=debug
sudo ./cgtproxy

# other shell
sudo nft list ruleset
```

I add some nft package counter for debug rules.
