### ISSUE TITLE
cgtproxy无法启动

### ISSUE THREAD

**Issue by Bryan2333** [black-desk/cgtproxy#258]
RT

我的系统是Arch Linux

cgtproxy无法启动不管是用systemd service还是直接在终端里面启动。

报错
```
1.7392784577036908e+09  info    cgtproxy        Cgroup mount point auto detection done. {"cgroup root": "/sys/fs/cgroup"}
Error: 
create nft table mananger: flush initial content: create table: conn.Receive: netlink receive: file exists
```

下面是我的配置文件
<details>

```
# This file is my daily use configuration,
# I use it to show how to use cgtproxy with clash-meta.
#
# Further configuration documentation can be found at
# https://godoc.org/github.com/black-desk/cgtproxy/pkg/cgtproxy/config

version: 1
cgroup-root: AUTO # path to cgroupfs v2 mount point or "AUTO"
route-table: 300

# This means any traffic send to 127.0.0.1 and ::1 will be directly send
# without influenced by the following configuration.
bypass:
  - 0.0.0.0/8
  - 10.0.0.0/8
  - 100.64.0.0/10
  - 127.0.0.0/8
  - 169.254.0.0/16
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 224.0.0.0/4
  - 240.0.0.0/4
  - 255.255.255.255
  - ::/128
  - ::1/128
  - 64:ff9b::/96
  - 100::/64
  - 2001::/32
  - 2001:20::/28
  - fe80::/10
  - ff00::/8

tproxies:
  sing-box:
    mark: 666
    port: 7894

    # Do not proxy UDP traffic. They will be send directly.
    # no-udp: false

    # Do not proxy IPv6 traffic. They will be send directly.
    no-ipv6: false

    # Hijack all IPv4 traffic which destination port is 53
    # and redirect them to ip:port.
    # This field is optional.
    dns-hijack:
      ip: 127.0.0.1
      port: 7894

# Rules are matched in order.
# `match` is an regex to match the cgroup path.
# `direct` means the traffic will not be redirect to any TPROXY server;
# `drop` means the traffic will be drop;
# `tproxy` means the traffic will be redirect to that TPROXY server.
#
# NOTE: You can use systemd-cgls to check the cgroup layout on your system.
#
# NOTE: Any web service will provide their service directly.
#       Traffics in connection created by remote host
#       will never redirect to TPROXY server or drop.
rules:
  # This rule match the clash-meta core.
  # Make cgtproxy produce nft rules that
  # route the network traffic comes from this cgroupfs as usual.
  - # AUR packages `clash-meta` and `clash-meta-bin`
    # contains the `clash-meta` systemd service,
    # which will be launched by systemd
    # in cgroup `/system.slice/clash-meta.service`.
    # But [my clash-meta deb package](https://github.com/black-desk/debs/tree/master/one.metacubex.clash-meta)
    # use a systemd service name `one.metacubex.clash-meta`.
    match: |-
      \/system\.slice\/system-naiveproxy\.slice\/naiveproxy@.\.service
    direct: true

  - match: |-
      \/system\.slice\/sing-box\.service
    direct: true

  # Same as above.
  # Let's configure the user-level `cgtproxy-direct.slice`,
  # `cgtproxy-proxy.slice` and `cgtproxy-drop.slice` cgroup.
  #
  # Using this setup, you can start a non-proxy shell
  # by execute:
  #
  # ```bash
  # systemd-run --user --slice cgtproxy-direct.slice --shell
  # ```
  #
  # The command above start the new shell in a cgroup like
  # `/user.slice/user-1000.slice/user@1000.service/cgtproxy.slice/cgtproxy-direct.slice/run-u22.service`,
  # which match the regex in your configuration.
  # Then cgtproxy will produce nft rules to
  # make that `run-u22.service` get rid of transparent proxy.
  - match: |-
      \/user\.slice\/user-\d+\.slice/user@\d+\.service\/cgtproxy\.slice\/cgtproxy-direct\.slice\/.*
    direct: true
  - match: |-
      \/user\.slice\/user-\d+\.slice/user@\d+\.service\/cgtproxy\.slice\/cgtproxy-drop\.slice\/.*
    drop: true
  - match: |-
      \/user\.slice\/user-\d+\.slice/user@\d+\.service\/cgtproxy\.slice\/cgtproxy-proxy\.slice\/.*
    tproxy: sing-box

  # Application related rules:
  # To make these rules working across desktop environments,
  # please take a look on https://systemd.io/DESKTOP_ENVIRONMENTS/.
  # NOTE:
  # | Desktop Environment | Launcher    |
  # |---------------------|-------------|
  # | GNOME               | `"gnome"`   |
  # | dde                 | `"DDE"`     |
  # | KDE                 | none        |
  # | flatpak             | `"flatpak"` |
  # So we should use
  # ```
  # \/user\.slice\/user-\d+\.slice\/user@\d+\.service\/app\.slice\/app(?:-(?:gnome|DDE|flatpak))?-APPID(?:-.+\.scope|(?:@.+)?\.service)
  # ```
  # to match application named `APPID`.
  # Check https://regex101.com/r/BgZcws/2 for example application cgroup names.

  # https://parsec.app/
  # `parsec` should always connect to network directly.
  - match: |-
      \/user\.slice\/user-\d+\.slice\/user@\d+\.service\/app\.slice\/app(?:-(?:gnome|DDE|flatpak))?-(?:parsecd|com\.parsecgaming\.parsec)(?:-.+\.scope|(?:@.+)?\.service)
    direct: true

  # For any cgroup else, TPROXY to clash-meta.
  - match: |-
      \/.*
    tproxy: sing-box
```

</details>

**Comment by Bryan2333** [comment]
看过了，我用pgrep确认过没有cgtproxy正在运行，还有那几条删除防火墙规则和路由表的命令我也执行了。但是就是启动不。

**Comment by black-desk** [comment]
我看一下 刚好有空 我这边已经复现到了

**Comment by black-desk** [comment]
原因是你的bypass里面有个特殊的地址 255.255.255.255 我实现ip set的方式比较黑，你这ip搞一下ipv4溢出成ipv6了 全乱了

**Comment by black-desk** [comment]
2025-02-11T21:31:57.477+0800    INFO    cgtproxy        Cgroup mount point auto detection done. {"cgroup root": "/sys/fs/cgroup"}
2025-02-11T21:31:57.477+0800    DEBUG   cgtproxy        Create a cgroupv2 filesystem monitor.
2025-02-11T21:31:57.477+0800    DEBUG   cgtproxy        Initialing nft table structure.
2025-02-11T21:31:57.477+0800    DEBUG   cgtproxy        Last IP in net 127.0.0.0/8 is 127.255.255.255
2025-02-11T21:31:57.477+0800    DEBUG   cgtproxy        Next IP of 127.255.255.255 is 128.0.0.0
2025-02-11T21:31:57.477+0800    DEBUG   cgtproxy        Next IP of 255.255.255.255 is ::1:0:0:0
2025-02-11T21:31:57.477+0800    DEBUG   cgtproxy        Last IP in net ::1/128 is ::1
2025-02-11T21:31:57.477+0800    DEBUG   cgtproxy        Next IP of ::1 is ::2
2025-02-11T21:31:57.477+0800    DEBUG   cgtproxy        Refilling output chain.
Error:
/home/black_desk/Documents/workspace/repos/source/cgtproxy/pkg/nftman/new.go:82 (82a345)
        create nft table mananger
/home/black_desk/Documents/workspace/repos/source/cgtproxy/pkg/nftman/new.go:226 (82aaf6)
        flush initial content
conn.Receive: netlink receive: invalid argument

**Comment by black-desk** [comment]
直接的错误是上面这个，
你贴的那个：
create nft table mananger: flush initial content: create table: conn.Receive: netlink receive: file exists
是因为因为上面那样的原因失败了一次，然后我这个程序异常退出的时候没有把已经建出来的表删掉，重新启动建表的时候就提示已存在了。

**Comment by black-desk** [comment]
问题肯定是我的问题，我的异常退出清理没做好。
这里有几个说法：

1. 这个项目里的bypass的功能和你想的可能不太一样，在透明代理这个语境下，没有必要在这里提前bypass掉太多东西，因为你的singbox那边也有一层bypass；
2. 我的ip set的实现可能需要调整一下，这个我得想想怎么搞比较合适；
3. 我程序异常退出的时候应该少了一个错误处理。

建议你先：
1. 和我给出的示例配置一样 这里只处理127.0.0.0/8和::1/128
2. 如果你出于一些原因希望提前bypass掉更多地址范围，先不要写255.255.255.255，等我把bug修了

**Comment by Bryan2333** [comment]
好的，我这边把255.255.255.255删掉后，就可以成功启动了。

**Comment by Bryan2333** [comment]
你好，我这个启动成功后，dns一直解析失败。

这是我clash-meta的配置
<details>

```
allow-lan: false # 允许局域网连接

bind-address: "*" # 绑定 IP 地址，仅作用于 allow-lan 为 true，'*'表示所有地址

skip-auth-prefixes: # 设置跳过验证的 IP 段
  - 127.0.0.1/8
  - ::1/128

find-process-mode: off

mode: rule

geodata-mode: true

geodata-loader: memconservative

geosite-matcher: mph

log-level: info

ipv6: true 

external-controller: 127.0.0.1:9093

external-ui: /usr/share/metacubexd/

routing-mark: 6666

profile: 
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com

dns:
  enable: true
  prefer-h3: false
  listen: 0.0.0.0:5333
  ipv6: false
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: redir-host
  respect-rules: false

proxies:
  - name: "akko"
    type: socks5
    server: 127.0.0.1
    port: 1081
    ip-version: ipv4

  - name: "dns-out"
    type: dns

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - DIRECT
      - akko

rules:
  - DST-PORT,53,dns-out
  - NETWORK,udp,DIRECT
  - IN-PORT,30000,DIRECT
  - GEOSITE,private,DIRECT
  - GEOSITE,microsoft@cn,DIRECT  
  - GEOSITE,apple@cn,DIRECT  
  - GEOSITE,google@cn,DIRECT  
  - GEOSITE,jetbrains@cn,DIRECT  
  - GEOSITE,cn,DIRECT  
  - DOMAIN-REGEX,^(download|download-cdn)\\.jetbrains\\.com$,DIRECT
  - DOMAIN-REGEX,.*ustclug\\.org$,DIRECT
  - GEOSITE,geolocation-!cn,Proxy
  - GEOSITE,bytedance@!cn,Proxy
  - GEOSITE,tiktok,Proxy
  - GEOIP,cn,DIRECT
  - GEOIP,private,DIRECT
  - MATCH,Proxy

listeners:
  - name: direct-only-v4
    type: mixed
    port: 30000
    listen: 127.0.0.1

  - name: direct-only-v6
    type: mixed
    port: 30000
    listen: ::1

  - name: mixed-in-v4
    type: mixed
    port: 7890
    listen: 127.0.0.1

  - name: mixed-in-v6
    type: mixed
    port: 7890
    listen: ::1

  - name: tproxy-in-v4
    type: tproxy
    port: 7894
    listen: 127.0.0.1

  - name: tproxy-in-v6
    type: tproxy
    port: 7894
    listen: ::1

```

</details>

这是我cgtproxy的配置

<details>

```
version: 1
cgroup-root: AUTO
route-table: 300

bypass:
  - 127.0.0.0/8
  - ::1

tproxies:
  clash-meta:
    mark: 6666
    port: 7894
    no-udp: false
    no-ipv6: false
    dns-hijack:
      ip: 127.0.0.1
      port: 5333

rules:
  - match: |-
      \/system\.slice\/system-naiveproxy\.slice\/naiveproxy.*\.service
    direct: true

  - match: |-
      \/system\.slice\/clash-meta\.service
    direct: true

  - match: |-
      \/system.slice\/NetworkManager\.service
    direct: true

  - match: |-
      \/user\.slice\/user-\d+\.slice/user@\d+\.service\/cgtproxy\.slice\/cgtproxy-direct\.slice\/.*
    direct: true

  - match: |-
      \/user\.slice\/user-\d+\.slice/user@\d+\.service\/cgtproxy\.slice\/cgtproxy-drop\.slice\/.*
    drop: true
    
  - match: |-
      \/user\.slice\/user-\d+\.slice/user@\d+\.service\/cgtproxy\.slice\/cgtproxy-proxy\.slice\/.*
    tproxy: clash-meta

  - match: |-
      \/.*
    tproxy: clash-meta

```

</details>

启动cgtproxy后，我尝试用dig向clash-meta监听的5333端口查询dns，结果A记录都是空的。

```
bryan on Bryan-YOGA14s in /etc/clash-meta 󰌾 
❯ dig @127.0.0.1 v2ex.com -p 5333

; <<>> DiG 9.20.5 <<>> @127.0.0.1 v2ex.com -p 5333
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 57696
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;v2ex.com.                      IN      A

;; Query time: 0 msec
;; SERVER: 127.0.0.1#5333(127.0.0.1) (UDP)
;; WHEN: Wed Feb 12 00:35:59 CST 2025
;; MSG SIZE  rcvd: 26
```

请教一下这是什么问题？
